[package]
name = "nimby_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
binrw = "0.15.0"
half = "2.4.1"
image = "0.25"
wyhash = "0.6.0"
serde_json = "1"
zstd = "0.13.3"

[[bin]]
name = "nimby_gen"
path = "src/main.rs"

[[bin]]
name = "visualize"
path = "src/visualize.rs"

[[bin]]
name = "generate"
path = "src/generate.rs"

[[bin]]
name = "inject"
path = "src/inject.rs"

[[bin]]
name = "hashtest"
path = "src/hashtest.rs"

[[bin]]
name = "import_orm"
path = "src/import_orm.rs"

[[bin]]
name = "dump_branches"
path = "src/dump_branches.rs"
