[package]
name = "turnout-cli"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
turnout-core = { path = "../core" }
anyhow = "1.0"
image = "0.25"
serde_json = "1"
dirs-next = "2.0"

[[bin]]
name = "turnout"
path = "src/main.rs"

[[bin]]
name = "generate"
path = "src/generate.rs"

[[bin]]
name = "inject"
path = "src/inject.rs"

[[bin]]
name = "import_orm"
path = "src/import_orm.rs"

[[bin]]
name = "dump_branches"
path = "src/dump_branches.rs"

[[bin]]
name = "compare_orm"
path = "src/compare_orm.rs"

[[bin]]
name = "check_coords"
path = "src/check_coords.rs"

[[bin]]
name = "verify_coords"
path = "src/verify_coords.rs"

