[package]
name = "nimby-gen-cli"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
nimby-gen-core = { path = "../core" }
anyhow = "1.0"
image = "0.25"
serde_json = "1"
zstd = "0.13"

[[bin]]
name = "nimby_gen"
path = "src/main.rs"

[[bin]]
name = "generate"
path = "src/generate.rs"

[[bin]]
name = "inject"
path = "src/inject.rs"

[[bin]]
name = "hashtest"
path = "src/hashtest.rs"

[[bin]]
name = "import_orm"
path = "src/import_orm.rs"

[[bin]]
name = "dump_branches"
path = "src/dump_branches.rs"

[[bin]]
name = "compare_orm"
path = "src/compare_orm.rs"
