[package]
name = "orm-bench"
version = "0.0.0"
edition = "2024"
publish = false

[lints]
workspace = true

[[bin]]
name = "orm-bench"
path = "src/main.rs"

[dependencies]
maplibre_native = { git = "https://github.com/SuperManifolds/maplibre-native-rs", rev = "29f4464", features = ["json", "tokio"] }
serde_json = "1.0"
